[project]
name = "quantumintegralreduction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "galois>=0.4.6",
    "numpy>=2.0,<2.3",
    "numba",
    "matplotlib",
    "pysr",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
